# Form implementation generated from reading ui file '..\main_window.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(737, 799)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_17 = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout.addWidget(self.label_17)
        self.units_combo = QtWidgets.QComboBox(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.units_combo.sizePolicy().hasHeightForWidth())
        self.units_combo.setSizePolicy(sizePolicy)
        self.units_combo.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.units_combo.setFont(font)
        self.units_combo.setObjectName("units_combo")
        self.horizontalLayout.addWidget(self.units_combo)
        self.unit_create = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unit_create.sizePolicy().hasHeightForWidth())
        self.unit_create.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.unit_create.setFont(font)
        self.unit_create.setObjectName("unit_create")
        self.horizontalLayout.addWidget(self.unit_create)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(50, -1, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.users_total = QtWidgets.QLabel(parent=self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.users_total.setFont(font)
        self.users_total.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.users_total.setObjectName("users_total")
        self.gridLayout.addWidget(self.users_total, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.radio_users = QtWidgets.QLabel(parent=self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.radio_users.setFont(font)
        self.radio_users.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.radio_users.setObjectName("radio_users")
        self.gridLayout.addWidget(self.radio_users, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.channels_create = QtWidgets.QPushButton(parent=self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.channels_create.setFont(font)
        self.channels_create.setObjectName("channels_create")
        self.verticalLayout_2.addWidget(self.channels_create)
        self.gen_diagram = QtWidgets.QPushButton(parent=self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.gen_diagram.setFont(font)
        self.gen_diagram.setObjectName("gen_diagram")
        self.verticalLayout_2.addWidget(self.gen_diagram)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(50, -1, -1, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.nets_total = QtWidgets.QLabel(parent=self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.nets_total.setFont(font)
        self.nets_total.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.nets_total.setObjectName("nets_total")
        self.gridLayout_2.addWidget(self.nets_total, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.nets_configured = QtWidgets.QLabel(parent=self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.nets_configured.setFont(font)
        self.nets_configured.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.nets_configured.setObjectName("nets_configured")
        self.gridLayout_2.addWidget(self.nets_configured, 1, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.channels_setup = QtWidgets.QPushButton(parent=self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.channels_setup.setFont(font)
        self.channels_setup.setObjectName("channels_setup")
        self.verticalLayout_3.addWidget(self.channels_setup)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(50, -1, -1, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_9 = QtWidgets.QLabel(parent=self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 1)
        self.devs_total_configured = QtWidgets.QLabel(parent=self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.devs_total_configured.setFont(font)
        self.devs_total_configured.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.devs_total_configured.setObjectName("devs_total_configured")
        self.gridLayout_3.addWidget(self.devs_total_configured, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(parent=self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 1, 0, 1, 1)
        self.devs_4400 = QtWidgets.QLabel(parent=self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.devs_4400.setFont(font)
        self.devs_4400.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.devs_4400.setObjectName("devs_4400")
        self.gridLayout_3.addWidget(self.devs_4400, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(parent=self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 2, 0, 1, 1)
        self.devs_4800 = QtWidgets.QLabel(parent=self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.devs_4800.setFont(font)
        self.devs_4800.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.devs_4800.setObjectName("devs_4800")
        self.gridLayout_3.addWidget(self.devs_4800, 2, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(parent=self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 3, 0, 1, 1)
        self.devs_4600 = QtWidgets.QLabel(parent=self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.devs_4600.sizePolicy().hasHeightForWidth())
        self.devs_4600.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.devs_4600.setFont(font)
        self.devs_4600.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.devs_4600.setObjectName("devs_4600")
        self.gridLayout_3.addWidget(self.devs_4600, 3, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_3)
        # self.firmware_create = QtWidgets.QPushButton(parent=self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(
        #     self.firmware_create.sizePolicy().hasHeightForWidth()
        # )
        # self.firmware_create.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        # self.firmware_create.setFont(font)
        # self.firmware_create.setObjectName("firmware_create")
        # self.verticalLayout_4.addWidget(self.firmware_create)
        self.verticalLayout.addWidget(self.groupBox_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 737, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.MinimumExpanding,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_17.setText(_translate("MainWindow", "Підрозділ або частина"))
        self.unit_create.setText(_translate("MainWindow", "Створити нову"))
        self.groupBox.setTitle(_translate("MainWindow", "Особовий склад"))
        self.label.setText(_translate("MainWindow", "Всього"))
        self.users_total.setText(_translate("MainWindow", "50"))
        self.label_2.setText(_translate("MainWindow", "З раціями"))
        self.radio_users.setText(_translate("MainWindow", "40"))
        self.channels_create.setText(
            _translate("MainWindow", "Надати рації і створити канали")
        )
        self.gen_diagram.setText(_translate("MainWindow", "Сгенерувати схему зв'язку"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Канали"))
        self.label_5.setText(_translate("MainWindow", "Всього"))
        self.nets_total.setText(_translate("MainWindow", "15"))
        self.label_6.setText(_translate("MainWindow", "Повністю налаштовані"))
        self.nets_configured.setText(_translate("MainWindow", "0"))
        self.channels_setup.setText(_translate("MainWindow", "Налаштувати канали"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Рації"))
        self.label_9.setText(_translate("MainWindow", "Всього / Є прошивка"))
        self.devs_total_configured.setText(_translate("MainWindow", "42/0"))
        self.label_11.setText(_translate("MainWindow", "DP 4400"))
        self.devs_4400.setText(_translate("MainWindow", "30/0"))
        self.label_13.setText(_translate("MainWindow", "DP 4800"))
        self.devs_4800.setText(_translate("MainWindow", "10/0"))
        self.label_15.setText(_translate("MainWindow", "DM 4600"))
        self.devs_4600.setText(_translate("MainWindow", "2/0"))
        # self.firmware_create.setText(_translate("MainWindow", "Створити прошивку"))

